### ISSUE TITLE
hyh - BucketTake rewards can go to an insolvent bucket

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-09-ajna-judging#59]
hyh

medium

# BucketTake rewards can go to an insolvent bucket
## Summary

`_rewardBucketTake()` adds bucket take rewards in a form of bucket LP, but doesn't check for bucket bankruptcy.

## Vulnerability Detail

As all the subsequent operations deal only with LPs added later than bankruptcy time it doesn't make sense to add rewards to a bucket at the moment of its bankruptcy, they will be lost for beneficiaries.

## Impact

If `bankruptcyTime == block.timestamp` during `bucketTake()` then all the rewards will be lost for beneficiaries, i.e. both taker and kicker will not be able to withdraw anything.

## Code Snippet

`_rewardBucketTake()` doesn't check the bucket for being bankrupt at the current block (and `bankruptcyTime` isn't read and checked before that):

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/TakerActions.sol#L607-L651

```solidity
    function _rewardBucketTake(
        ...
    ) internal {
        Bucket storage bucket = buckets_[bucketIndex_];

>>      uint256 bankruptcyTime = bucket.bankruptcyTime;
        uint256 scaledDeposit  = Maths.wmul(vars.unscaledDeposit, vars.bucketScale);
        uint256 totalLPReward;
        uint256 takerLPReward;
        uint256 kickerLPReward;

        // if arb take - taker is awarded collateral * (bucket price - auction price) worth (in quote token terms) units of LPB in the bucket
        if (!depositTake_) {
            takerLPReward = Buckets.quoteTokensToLP(
                bucket.collateral,
                bucket.lps,
                scaledDeposit,
                Maths.wmul(vars.collateralAmount, vars.bucketPrice - vars.auctionPrice),
                vars.bucketPrice,
                Math.Rounding.Down
            );
            totalLPReward = takerLPReward;

>>          Buckets.addLenderLP(bucket, bankruptcyTime, msg.sender, takerLPReward);
        }

        // the bondholder/kicker is awarded bond change worth of LPB in the bucket
        if (vars.isRewarded) {
            kickerLPReward = Buckets.quoteTokensToLP(
                bucket.collateral,
                bucket.lps,
                scaledDeposit,
                vars.bondChange,
                vars.bucketPrice,
                Math.Rounding.Down
            );
            totalLPReward  += kickerLPReward;

>>          Buckets.addLenderLP(bucket, bankruptcyTime, vars.kicker, kickerLPReward);
```

So, if `bankruptcyTime == block.timestamp` at the time of `bucketTake()` then `lender.depositTime` will be set to `bucket.bankruptcyTime`:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/internal/Buckets.sol#L77-L91

```solidity
    function addLenderLP(
        ...
    ) internal {
        if (lpAmount_ != 0) {
            Lender storage lender = bucket_.lenders[lender_];

            if (bankruptcyTime_ >= lender.depositTime) lender.lps = lpAmount_;
            else lender.lps += lpAmount_;

>>          lender.depositTime = block.timestamp;
        }
    }
```

And both taker and kicker will not be able to withdraw any funds thereafter as their LP balance will be deemed empty:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/LenderActions.sol#L516-L520

```solidity
        Lender storage lender = bucket.lenders[msg.sender];

        uint256 lenderLpBalance;
>>      if (bucket.bankruptcyTime < lender.depositTime) lenderLpBalance = lender.lps;
        if (lenderLpBalance == 0 || lpAmount_ > lenderLpBalance) revert InsufficientLP();
```

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/LenderActions.sol#L411-L415

```solidity
        uint256 depositTime = lender.depositTime;

        RemoveDepositParams memory removeParams;

>>      if (bucket.bankruptcyTime < depositTime) removeParams.lpConstraint = lender.lps;
```

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/LenderActions.sol#L271-L275

```solidity
        vars.fromBucketDepositTime = fromBucketLender.depositTime;

        vars.toBucketPrice         = _priceAt(params_.toIndex);

>>      if (fromBucket.bankruptcyTime < vars.fromBucketDepositTime) vars.fromBucketLenderLP = fromBucketLender.lps;
```

## Tool used

Manual Review

## Recommendation

For uniformity consider adding the similar check to `_rewardBucketTake()`:

https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/TakerActions.sol#L607-L618

```diff
    function _rewardBucketTake(
        ...
    ) internal {
        Bucket storage bucket = buckets_[bucketIndex_];

        uint256 bankruptcyTime = bucket.bankruptcyTime;
+       
+       // cannot deposit bucket take rewards in the same block when bucket becomes insolvent
+       if (bankruptcyTime_ == block.timestamp) revert BucketBankruptcyBlock();
```

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue should be invalid because the bucket used for a `bucketTake` cannot be bankrupt in that same block. 
> 
> The bucket used in a `bucketTake` must hold some deposits in order to perform the `bucketTake` action. If a bucket is declared bankrupt in that same block, it means that there's no deposits in that bucket to perform a `bucketTake`. 
> 
> Bucket will be declared bankrupt if deposits are 0.
> ```solidity
> if (bucketCollateral == 0 && bucketDeposit == 0 && bucketLP != 0) {
>     bucket.lps            = 0;
>     bucket.bankruptcyTime = block.timestamp;
> }
> ```
> 
> Function `_takeBucket` will revert if deposits are zero in the specified bucket:
> https://github.com/sherlock-audit/2023-09-ajna/blob/main/ajna-core/src/libraries/external/TakerActions.sol#L438
> ```solidity
> // revert if no quote tokens in arbed bucket
> if (vars_.unscaledDeposit == 0) revert InsufficientLiquidity();
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neeksec** [comment]
Invalid. Agree with Escalation.

**Comment by Evert0x** [comment]
@dmitriia any comment on this?

**Comment by dmitriia** [comment]
> @dmitriia any comment on this?

There is also settlement logic that can make bucket bankrupt with `vars_.unscaledDeposit > 0`, so `bucketTake()` will not revert. Settlement of one borrower can happen in the same block as `bucketTake()` for another.

https://github.com/sherlock-audit/2023-09-ajna-dmitriia/blob/d8b173d43482ef50c1fafb05ff1aef6fda4a3c82/ajna-core/src/libraries/external/SettlerActions.sol#L480-L494

```solidity
            Bucket storage hpbBucket = buckets_[index];
            uint256 bucketLP = hpbBucket.lps;
            // If the remaining deposit and resulting bucket collateral is so small that the exchange rate
            // rounds to 0, then bankrupt the bucket.  Note that lhs are WADs, so the
            // quantity is naturally 1e18 times larger than the actual product
>>          if (depositRemaining * Maths.WAD + hpbBucket.collateral * _priceAt(index) <= bucketLP) {
                // existing LP for the bucket shall become unclaimable
                hpbBucket.lps            = 0;
>>              hpbBucket.bankruptcyTime = block.timestamp; // @audit can happen for some positive depositRemaining

                emit BucketBankruptcy(
                    index,
                    bucketLP
                );
            }
```

**Comment by santipu03** [comment]
> There is also settlement logic that can make bucket bankrupt with vars_.unscaledDeposit > 0, so bucketTake() will not revert. Settlement of one borrower can happen in the same block as bucketTake() for another.

If the bucket goes bankrupt with the settlement logic you pointed out, `vars_.unscaledDeposit` will always be 0 or a dust amount so the rewards lost (in case there are some) will always be 0 or a dust amount with no value at all. 
Look at #41 for reference.

**Comment by dmitriia** [comment]
This looks to be true, agree that this is low severity.

**Comment by Czar102** [comment]
Result:
Low
Unique

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- Expected severity: **false**. Actual severity: **medium**.
- Expected issue to be **open**. Actual issue is **closed**.
- [santipu03's escalation](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/59/#issuecomment-1799258702) could not be resolved, because it has 0 or more than 1 judge reactions.
